---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - php
        - python
        - ruby
  #  eslint:
  #    enabled: true
  #  fixme:
  #    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths: []
